services:
  postgres:
    image: postgres:17
    container_name: estoque-postgres

    environment:
      POSTGRES_DB: estoque_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    
    restart: unless-stopped
  
volumes:
  postgres_data: